language: node_js
node_js:
  - "10.14.2"

cache: npm

branches:
  except:
    - gh-pages

before_install:
  - cd dashboard/scripts/
  - npm install && npm run build
  - cp ./results/mentors.json ../client/assets/mentors.json
  - cd ../client/

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  local-dir: ./dashboard/client/dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
